PythonVersion="3.11"
packagedir=".python_packages/lib/site-packages"
OperationId="|+kfu11sZw9k=.c16a6f13_"
SourceDirectoryInBuildContainer="/tmp/zipdeploy/extracted"
PlatformName="python"
CompressDestinationDir="false"
