name: Build and deploy Python project to Azure Function App - helloworld-func-app

on:
  push:
    branches:
      - develop
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' 
  PYTHON_VERSION: '3.9' 

jobs:
  build-and-deploy: # build와 deploy를 하나로 합침
    runs-on: ubuntu-latest
    permissions:
      id-token: write 
      contents: read 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      # 1. 빌드 (Zip 생성)
      - name: Zip artifact for deployment
        run: |
          zip release.zip ./* -r -x "venv/*" -x ".git/*" -x ".github/*"

      # 2. Azure 로그인 (바로 진행)
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D4AF27ABA4A2427984D95D1ABF82774F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_2C3AA4921BB94A17A11B85A23F540B9F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4B1A43FD862046039E4C9B28766C3C74 }}

      # 3. 배포 (업로드/다운로드 과정 생략)
      - name: 'Deploy to Azure Functions'
        uses: Azure/functions-action@v1
        id: deploy-to-function
        with:
          app-name: 'helloworld-func-app'
          slot-name: 'Production'
          package: 'release.zip' # 위에서 만든 파일 바로 참조
