name: Trigger auto deployment for helloworld-container-app-v1

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ feat/add-chat-endpoints ]
    paths:
    - '**'
    - '.github/workflows/helloworld-container-app-v1-AutoDeployTrigger-7005161a-819c-4844-be9d-8ebeb2d69479.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.HELLOWORLDCONTAINERAPPV1_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.HELLOWORLDCONTAINERAPPV1_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.HELLOWORLDCONTAINERAPPV1_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: helloworldacr001.azurecr.io
          registryUsername: ${{ secrets.HELLOWORLDCONTAINERAPPV1_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.HELLOWORLDCONTAINERAPPV1_REGISTRY_PASSWORD }}
          containerAppName: helloworld-container-app-v1
          resourceGroup: helloworld_resource_group
          imageToBuild: helloworldacr001.azurecr.io/helloworld-container-app-v1:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


